// src/lib/components/shared/EmptyState.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button/index.js';
  import * as Card from '$lib/components/ui/card/index.js';

  type Props = {
    title: string;
    description: string;
    actionText?: string;
    onAction?: () => void;
  };

  let { title, description, actionText, onAction }: Props = $props();
</script>

<Card.Root class="rounded-none border-dashed text-center">
  <Card.Content class="space-y-3 px-4 py-8">
    <Card.Title>{title}</Card.Title>
    <Card.Description>{description}</Card.Description>
    {#if actionText && onAction}
      <div class="pt-1">
        <Button type="button" onclick={onAction}>{actionText}</Button>
      </div>
    {/if}
  </Card.Content>
</Card.Root>

// src/lib/components/shared/EmptyState.tsx
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardTitle,
} from "@/components/ui/card"

type EmptyStateProps = {
  title: string
  description: string
  actionText?: string
  onAction?: () => void
}

export function EmptyState({
  title,
  description,
  actionText,
  onAction,
}: EmptyStateProps) {
  return (
    <Card className="rounded-none border-dashed text-center">
      <CardContent className="space-y-3 px-4 py-8">
        <CardTitle>{title}</CardTitle>
        <CardDescription>{description}</CardDescription>
        {actionText && onAction ? (
          <div className="pt-1">
            <Button type="button" onClick={onAction}>
              {actionText}
            </Button>
          </div>
        ) : null}
      </CardContent>
    </Card>
  )
}
