// src/App.tsx
import { useEffect, useMemo, useState } from "react"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

import { seedIfNeeded } from "./lib/db/seed"
import { db } from "./lib/db/database"
import { filterAndSortCards } from "./lib/services/filterService"
import { activeBoardIdStore, boardsStore } from "./lib/stores/boards"
import { cardsStore } from "./lib/stores/cards"
import { columnsStore } from "./lib/stores/columns"
import { filtersStore } from "./lib/stores/filters"
import { toastStore } from "./lib/stores/ui"
import { useStore } from "./lib/stores/store"
import { useNotifications } from "./lib/hooks/useNotifications"
import { useConfirm } from "./lib/hooks/useConfirm"
import { useDataLoader } from "./lib/hooks/useDataLoader"
import { useBoardActions } from "./lib/hooks/useBoardActions"
import { useColumnActions } from "./lib/hooks/useColumnActions"
import { useCardActions } from "./lib/hooks/useCardActions"
import { useFilters } from "./lib/hooks/useFilters"
import { BoardView } from "./lib/components/board/BoardView"
import { TableView } from "./lib/components/table/TableView"
import { BoardToolbar } from "./lib/components/shared/BoardToolbar"
import { Modal } from "./lib/components/shared/Modal"
import { ConfirmDialog } from "./lib/components/shared/ConfirmDialog"
import { EmptyState } from "./lib/components/shared/EmptyState"
import { DatePicker } from "./lib/components/shared/DatePicker"
import type { WindowWithMoxt } from "./lib/types"

export default function App() {
  const [loading, setLoading] = useState(true)
  const [currentUser, setCurrentUser] = useState<string | null>(null)

  const backendLabel = useMemo(
    () => (db.provider === "moxt" ? "moxt" : "indexeddb"),
    []
  )

  // Reactive store state
  const boards = useStore(boardsStore)
  const activeBoardId = useStore(activeBoardIdStore)
  const columns = useStore(columnsStore)
  const cards = useStore(cardsStore)
  const filters = useStore(filtersStore)
  const toast = useStore(toastStore)

  const activeBoard = useMemo(
    () => boards.find((b) => b.id === activeBoardId) ?? null,
    [boards, activeBoardId]
  )

  const availableTags = useMemo(
    () => [...new Set(cards.flatMap((c) => c.tags))].sort(),
    [cards]
  )

  const filteredCards = useMemo(
    () => filterAndSortCards(cards, columns, filters),
    [cards, columns, filters]
  )

  // Hooks
  const { notifySuccess, safely } = useNotifications()
  const confirm = useConfirm(safely)
  const { loadBoardData, reloadBoards } = useDataLoader()

  const boardActions = useBoardActions({
    reloadBoards,
    notifySuccess,
    safely,
    requestConfirm: confirm.request,
  })

  const columnActions = useColumnActions({
    loadBoardData,
    notifySuccess,
    safely,
    requestConfirm: confirm.request,
  })

  const cardActions = useCardActions({
    loadBoardData,
    notifySuccess,
    safely,
    requestConfirm: confirm.request,
  })

  const filtersActions = useFilters()

  // Bootstrap
  useEffect(() => {
    const run = async () => {
      try {
        await seedIfNeeded()
        await reloadBoards(true)
        const bridge = (window as WindowWithMoxt).moxt
        const member = bridge?.currentMember
        if (member) {
          setCurrentUser(member.displayName ?? member.email ?? null)
        }
      } finally {
        setLoading(false)
      }
    }
    void run()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Switch board when selector changes
  function handleSelectBoard(id: string): void {
    activeBoardIdStore.set(id)
    void loadBoardData(id)
  }

  return (
    <main className="app">
      {/* ── Header ── */}
      <header className="toolbar">
        <div className="toolbar-title">
          <h1>Moxt Kanban</h1>
          <span className="chip version-chip" aria-label="Application version">
            v{__APP_VERSION__}
          </span>
          <span className="chip backend-chip">Backend: {backendLabel}</span>
          {currentUser ? (
            <span className="chip user-chip">{currentUser}</span>
          ) : null}
        </div>

        <div className="toolbar-actions">
          {boards.length > 0 ? (
            <Select
              value={activeBoardId ?? ""}
              onValueChange={handleSelectBoard}
            >
              <SelectTrigger className="w-[200px]">
                <SelectValue placeholder="Select board" />
              </SelectTrigger>
              <SelectContent>
                {boards.map((b) => (
                  <SelectItem key={b.id} value={b.id}>
                    {b.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          ) : null}

          <Button type="button" size="sm" onClick={boardActions.openCreate}>
            + New Board
          </Button>

          {activeBoard ? (
            <>
              <Button
                type="button"
                size="sm"
                variant="outline"
                onClick={() => boardActions.openEdit(activeBoard)}
              >
                Edit Board
              </Button>
              <Button
                type="button"
                size="sm"
                variant="outline"
                onClick={columnActions.openCreate}
              >
                + Column
              </Button>
            </>
          ) : null}
        </div>
      </header>

      {/* ── Board Toolbar ── */}
      {activeBoard ? (
        <BoardToolbar
          boardName={activeBoard.name}
          viewMode={filters.viewMode}
          filters={filters}
          columns={columns}
          availableTags={availableTags}
          onToggleView={filtersActions.toggleView}
          onFiltersChange={filtersActions.update}
          onResetFilters={filtersActions.reset}
        />
      ) : null}

      {/* ── Content ── */}
      <section className="content-region">
        {loading ? (
          <p className="loading-hint">Loading…</p>
        ) : !activeBoard ? (
          <EmptyState
            title="No boards yet"
            description="Create your first board to get started."
            actionText="Create Board"
            onAction={boardActions.openCreate}
          />
        ) : filters.viewMode === "table" ? (
          <TableView
            cards={filteredCards}
            columns={columns}
            sortField={filters.sortField}
            sortDirection={filters.sortDirection}
            onSort={filtersActions.updateSort}
            onEditCard={cardActions.openEdit}
            onDeleteCard={cardActions.requestDelete}
          />
        ) : (
          <BoardView
            columns={columns}
            cards={filteredCards}
            onAddCard={cardActions.openCreate}
            onEditCard={cardActions.openEdit}
            onDeleteCard={cardActions.requestDelete}
            onDrop={cardActions.drop}
          />
        )}
      </section>

      {/* ── Toast ── */}
      {toast ? (
        <div
          className={`toast toast-${toast.type}`}
          role="status"
          aria-live="polite"
        >
          {toast.message}
        </div>
      ) : null}

      {/* ── Board Modal ── */}
      <Modal
        open={boardActions.modalOpen}
        title={boardActions.editingId ? "Edit Board" : "New Board"}
        onClose={boardActions.closeModal}
        width="sm"
      >
        <form
          className="form"
          onSubmit={(e) => {
            e.preventDefault()
            void boardActions.submit(
              boardActions.nameInput,
              boardActions.editingId
            )
          }}
        >
          <div>
            <Label htmlFor="board-name">Board Name</Label>
            <Input
              id="board-name"
              value={boardActions.nameInput}
              onChange={(e) => boardActions.setNameInput(e.target.value)}
              placeholder="Board name"
              required
            />
          </div>
          <div className="form-actions">
            {boardActions.editingId && activeBoard ? (
              <Button
                type="button"
                variant="destructive"
                onClick={() => boardActions.requestDelete(activeBoard)}
              >
                Delete Board
              </Button>
            ) : null}
            <div className="spacer" />
            <Button
              type="button"
              variant="outline"
              onClick={boardActions.closeModal}
            >
              Cancel
            </Button>
            <Button type="submit">
              {boardActions.editingId ? "Save" : "Create"}
            </Button>
          </div>
        </form>
      </Modal>

      {/* ── Column Modal ── */}
      <Modal
        open={columnActions.modalOpen}
        title={columnActions.editingId ? "Edit Column" : "New Column"}
        onClose={columnActions.closeModal}
        width="sm"
      >
        <form
          className="form"
          onSubmit={(e) => {
            e.preventDefault()
            void columnActions.submit(
              columnActions.titleInput,
              columnActions.editingId
            )
          }}
        >
          <div>
            <Label htmlFor="column-title">Column Title</Label>
            <Input
              id="column-title"
              value={columnActions.titleInput}
              onChange={(e) => columnActions.setTitleInput(e.target.value)}
              placeholder="Column title"
              required
            />
          </div>
          <div className="form-actions">
            <div className="spacer" />
            <Button
              type="button"
              variant="outline"
              onClick={columnActions.closeModal}
            >
              Cancel
            </Button>
            <Button type="submit">
              {columnActions.editingId ? "Save" : "Create"}
            </Button>
          </div>
        </form>
      </Modal>

      {/* ── Card Editor Modal ── */}
      <Modal
        open={cardActions.editor.open}
        title={cardActions.editor.editingCardId ? "Edit Card" : "New Card"}
        onClose={() =>
          cardActions.setEditor((prev) => ({ ...prev, open: false }))
        }
        width="lg"
      >
        <form
          className="form"
          onSubmit={(e) => {
            e.preventDefault()
            void cardActions.submit(cardActions.editor)
          }}
        >
          <div className="grid-2">
            <div>
              <Label htmlFor="card-title">Title</Label>
              <Input
                id="card-title"
                value={cardActions.editor.title}
                onChange={(e) =>
                  cardActions.setEditor((prev) => ({
                    ...prev,
                    title: e.target.value,
                  }))
                }
                placeholder="Card title"
                required
              />
            </div>

            <div>
              <Label htmlFor="card-column">Status (Column)</Label>
              <Select
                value={cardActions.editor.columnId}
                onValueChange={(v) =>
                  cardActions.setEditor((prev) => ({ ...prev, columnId: v }))
                }
              >
                <SelectTrigger id="card-column">
                  <SelectValue placeholder="Select column" />
                </SelectTrigger>
                <SelectContent>
                  {columns.map((col) => (
                    <SelectItem key={col.id} value={col.id}>
                      {col.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <div>
            <Label htmlFor="card-description">Description</Label>
            <Textarea
              id="card-description"
              value={cardActions.editor.description}
              onChange={(e) =>
                cardActions.setEditor((prev) => ({
                  ...prev,
                  description: e.target.value,
                }))
              }
              placeholder="Description (optional)"
              rows={3}
            />
          </div>

          <div className="grid-2">
            <div>
              <Label htmlFor="card-priority">Priority</Label>
              <Select
                value={cardActions.editor.priority}
                onValueChange={(v) =>
                  cardActions.setEditor((prev) => ({
                    ...prev,
                    priority: v as typeof prev.priority,
                  }))
                }
              >
                <SelectTrigger id="card-priority">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Low</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="urgent">Urgent</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Due Date</Label>
              <DatePicker
                value={cardActions.editor.dueDate || null}
                placeholder="Pick due date"
                onValueChange={(v) =>
                  cardActions.setEditor((prev) => ({
                    ...prev,
                    dueDate: v ?? "",
                  }))
                }
              />
            </div>
          </div>

          <div>
            <Label htmlFor="card-tags">Tags (comma-separated)</Label>
            <Input
              id="card-tags"
              value={cardActions.editor.tagsText}
              onChange={(e) =>
                cardActions.setEditor((prev) => ({
                  ...prev,
                  tagsText: e.target.value,
                }))
              }
              placeholder="e.g. frontend, bug, v2"
              list="card-tag-suggestions"
            />
            <datalist id="card-tag-suggestions">
              {availableTags.map((tag) => (
                <option key={tag} value={tag} />
              ))}
            </datalist>
          </div>

          <div className="form-actions">
            <div className="spacer" />
            <Button
              type="button"
              variant="outline"
              onClick={() =>
                cardActions.setEditor((prev) => ({ ...prev, open: false }))
              }
            >
              Cancel
            </Button>
            <Button type="submit">
              {cardActions.editor.editingCardId ? "Save" : "Create"}
            </Button>
          </div>
        </form>
      </Modal>

      {/* ── Confirm Dialog ── */}
      <ConfirmDialog
        open={confirm.state.open}
        title={confirm.state.title}
        message={confirm.state.message}
        confirmText="Confirm"
        cancelText="Cancel"
        onConfirm={() => void confirm.confirm(confirm.state.action)}
        onCancel={confirm.cancel}
      />
    </main>
  )
}

// src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import BoardToolbar from './lib/components/shared/BoardToolbar.svelte';
  import BoardView from './lib/components/board/BoardView.svelte';
  import ConfirmDialog from './lib/components/shared/ConfirmDialog.svelte';
  import DatePicker from './lib/components/shared/DatePicker.svelte';
  import EmptyState from './lib/components/shared/EmptyState.svelte';
  import Modal from './lib/components/shared/Modal.svelte';
  import TableView from './lib/components/table/TableView.svelte';
  import { Button } from '$lib/components/ui/button/index.js';
  import { Input } from '$lib/components/ui/input/index.js';
  import * as Select from '$lib/components/ui/select/index.js';
  import { Textarea } from '$lib/components/ui/textarea/index.js';
  import { db } from './lib/db/database';
  import { seedIfNeeded } from './lib/db/seed';
  import { filterAndSortCards } from './lib/services/filterService';
  import { initSync, destroySync } from './lib/services/syncService';
  import { activeBoardIdStore, boardsStore } from './lib/stores/boards';
  import { cardsStore } from './lib/stores/cards';
  import { columnsStore } from './lib/stores/columns';
  import { filtersStore } from './lib/stores/filters';
  import { toastStore } from './lib/stores/ui';
  import { createNotifications } from './lib/hooks/useNotifications.svelte';
  import { createConfirm } from './lib/hooks/useConfirm.svelte';
  import { createDataLoader } from './lib/hooks/useDataLoader.svelte';
  import { createBoardActions } from './lib/hooks/useBoardActions.svelte';
  import { createColumnActions } from './lib/hooks/useColumnActions.svelte';
  import { createCardActions } from './lib/hooks/useCardActions.svelte';
  import { createFilters } from './lib/hooks/useFilters.svelte';
  import type { Card, CardPriority } from './lib/types';

  // — hooks —
  const notify = createNotifications();
  const confirm = createConfirm(notify.safely);
  const loader = createDataLoader();
  const boards = createBoardActions({
    reloadBoards: loader.reloadBoards,
    notifySuccess: notify.notifySuccess,
    safely: notify.safely,
    requestConfirm: confirm.request,
  });
  const columns = createColumnActions({
    loadBoardData: loader.loadBoardData,
    notifySuccess: notify.notifySuccess,
    safely: notify.safely,
    requestConfirm: confirm.request,
  });
  const cards = createCardActions({
    loadBoardData: loader.loadBoardData,
    notifySuccess: notify.notifySuccess,
    safely: notify.safely,
    requestConfirm: confirm.request,
  });
  const filters = createFilters();

  // — app-level state —
  let loading = $state(true);
  let currentUser = $state<string | null>(null);

  const appVersion = __APP_VERSION__;

  const activeBoard = $derived(
    $boardsStore.find((board) => board.id === $activeBoardIdStore) ?? null,
  );

  const availableTags = $derived(
    [...new Set($cardsStore.flatMap((card) => card.tags.map((tag) => tag.trim()).filter(Boolean)))].sort(),
  );

  const visibleCards = $derived(filterAndSortCards($cardsStore, $columnsStore, $filtersStore));

  const activeBoardLabel = $derived(activeBoard?.name ?? 'Select Board');
  const backendProviderLabel = $derived(db.provider === 'moxt' ? 'moxt' : 'indexeddb');

  const cardPriorityLabel = $derived(cards.editor.priority);

  const cardColumnLabel = $derived.by(() => {
    return $columnsStore.find((col) => col.id === cards.editor.columnId)?.title ?? 'Select Column';
  });

  const cardsByColumn = $derived.by(() => {
    const grouped: Record<string, Card[]> = {};

    for (const column of $columnsStore) {
      grouped[column.id] = [];
    }

    for (const card of visibleCards) {
      if (!grouped[card.columnId]) {
        grouped[card.columnId] = [];
      }
      grouped[card.columnId].push(card);
    }

    for (const key of Object.keys(grouped)) {
      grouped[key].sort((a, b) => a.order - b.order);
    }

    return grouped;
  });

  onMount(async () => {
    try {
      await seedIfNeeded();
      await loader.reloadBoards(true);
      initSync();

      const m = (window as any).moxt?.currentMember;
      if (m) currentUser = m.displayName || m.email || null;
    } catch (error) {
      notify.notifyError(notify.parseError(error));
    } finally {
      loading = false;
    }
  });

  onDestroy(() => {
    destroySync();
  });

  async function selectBoard(boardId: string): Promise<void> {
    await notify.safely(async () => {
      activeBoardIdStore.set(boardId);
      await loader.loadBoardData(boardId);
    });
  }
</script>

<main>
  <header class="toolbar">
    <div class="toolbar-title">
      <h1>Moxt Kanban</h1>
      <span class="version-chip">{appVersion}</span>
      <span class="backend-chip" aria-label="Current backend provider">
        Backend: {backendProviderLabel}
      </span>
    </div>

    <div class="toolbar-actions">
      <Select.Root
        type="single"
        value={$activeBoardIdStore ?? ''}
        onValueChange={(value) => value && selectBoard(value)}
      >
        <Select.Trigger class="w-[220px]" disabled={$boardsStore.length === 0}>{activeBoardLabel}</Select.Trigger>
        <Select.Content>
          {#each $boardsStore as board (board.id)}
            <Select.Item value={board.id}>{board.name}</Select.Item>
          {/each}
        </Select.Content>
      </Select.Root>

      <Button type="button" onclick={boards.openCreate}>+ Board</Button>

      {#if activeBoard}
        <Button type="button" variant="outline" onclick={() => boards.openEdit(activeBoard)}>Edit Board</Button>
      {/if}

      {#if currentUser}
        <span class="user-chip" title="Logged in as {currentUser}">{currentUser}</span>
      {/if}
    </div>
  </header>

  {#if activeBoard}
    <BoardToolbar
      boardName={activeBoard.name}
      viewMode={$filtersStore.viewMode}
      filters={$filtersStore}
      columns={$columnsStore}
      {availableTags}
      onToggleView={filters.toggleView}
      onFiltersChange={filters.update}
      onResetFilters={filters.reset}
    />
  {/if}

  <section class="content-region">
    {#if loading}
      <p class="status">Loading...</p>
    {:else if !$activeBoardIdStore}
      <EmptyState
        title="No boards"
        description="Create your first board to start organizing work."
        actionText="Create Board"
        onAction={boards.openCreate}
      />
    {:else if $filtersStore.viewMode === 'board'}
      <BoardView
        columns={$columnsStore}
        {cardsByColumn}
        onAddColumn={columns.openCreate}
        onMoveColumnLeft={(column) => columns.move(column, 'left')}
        onMoveColumnRight={(column) => columns.move(column, 'right')}
        onEditColumn={columns.openEdit}
        onDeleteColumn={columns.requestDelete}
        onAddCard={cards.openCreate}
        onEditCard={cards.openEdit}
        onDeleteCard={cards.requestDelete}
        onDropCard={cards.drop}
      />
    {:else}
      <TableView
        cards={visibleCards}
        columns={$columnsStore}
        sortField={$filtersStore.sortField}
        sortDirection={$filtersStore.sortDirection}
        onSort={filters.updateSort}
        onEditCard={cards.openEdit}
        onDeleteCard={cards.requestDelete}
      />
    {/if}
  </section>

  <Modal
    open={boards.modalOpen}
    title={boards.editingId ? 'Edit Board' : 'Create Board'}
    onClose={boards.closeModal}
  >
    <form
      class="form"
      onsubmit={(event) => {
        event.preventDefault();
        void boards.submit();
      }}
    >
      <label>
        Name
        <Input bind:value={boards.nameInput} required />
      </label>
      <div class="form-actions">
        <Button type="button" variant="outline" onclick={boards.closeModal}>Cancel</Button>
        <Button type="submit">Save</Button>
      </div>
    </form>

    {#if boards.editingId}
      {@const editingBoard = $boardsStore.find((b) => b.id === boards.editingId)}
      {#if editingBoard}
        <div class="danger-zone">
          <p class="danger-zone-label">Danger Zone</p>
          <Button
            type="button"
            variant="destructive"
            onclick={() => {
              boards.closeModal();
              boards.requestDelete(editingBoard);
            }}
          >
            Delete Board
          </Button>
        </div>
      {/if}
    {/if}
  </Modal>

  <Modal
    open={columns.modalOpen}
    title={columns.editingId ? 'Rename Column' : 'Create Column'}
    onClose={columns.closeModal}
    width="sm"
  >
    <form
      class="form"
      onsubmit={(event) => {
        event.preventDefault();
        void columns.submit();
      }}
    >
      <label>
        Title
        <Input bind:value={columns.titleInput} required />
      </label>
      <div class="form-actions">
        <Button type="button" variant="outline" onclick={columns.closeModal}>Cancel</Button>
        <Button type="submit">Save</Button>
      </div>
    </form>
  </Modal>

  <Modal
    open={cards.editor.open}
    title={cards.editor.editingCardId ? 'Edit Card' : 'Create Card'}
    onClose={() => (cards.editor.open = false)}
    width="lg"
  >
    <form
      class="form"
      onsubmit={(event) => {
        event.preventDefault();
        void cards.submit();
      }}
    >
      <label>
        Title
        <Input bind:value={cards.editor.title} required />
      </label>

      <label>
        Description
        <Textarea rows={4} bind:value={cards.editor.description}></Textarea>
      </label>

      <div class="grid-2">
        <label>
          Priority
          <Select.Root
            type="single"
            value={cards.editor.priority}
            onValueChange={(value) =>
              (cards.editor = {
                ...cards.editor,
                priority: value as CardPriority,
              })}
          >
            <Select.Trigger class="w-full">{cardPriorityLabel}</Select.Trigger>
            <Select.Content>
              <Select.Item value="low">low</Select.Item>
              <Select.Item value="medium">medium</Select.Item>
              <Select.Item value="high">high</Select.Item>
              <Select.Item value="urgent">urgent</Select.Item>
            </Select.Content>
          </Select.Root>
        </label>

        <label>
          Status / Column
          <Select.Root
            type="single"
            value={cards.editor.columnId}
            onValueChange={(value) =>
              (cards.editor = {
                ...cards.editor,
                columnId: value,
              })}
          >
            <Select.Trigger class="w-full">{cardColumnLabel}</Select.Trigger>
            <Select.Content>
              {#each $columnsStore as column (column.id)}
                <Select.Item value={column.id}>{column.title}</Select.Item>
              {/each}
            </Select.Content>
          </Select.Root>
        </label>
      </div>

      <div class="grid-2">
        <label>
          Tags (comma separated)
          <Input bind:value={cards.editor.tagsText} placeholder="frontend, bug" />
        </label>

        <label>
          Due Date
          <DatePicker
            value={cards.editor.dueDate || null}
            placeholder="Pick due date"
            onValueChange={(value) =>
              (cards.editor = {
                ...cards.editor,
                dueDate: value ?? '',
              })}
          />
        </label>
      </div>

      <div class="form-actions">
        <Button type="button" variant="outline" onclick={() => (cards.editor.open = false)}>Cancel</Button>
        <Button type="submit">Save</Button>
      </div>
    </form>
  </Modal>

  <ConfirmDialog
    open={confirm.state.open}
    title={confirm.state.title}
    message={confirm.state.message}
    confirmText="Delete"
    cancelText="Cancel"
    onCancel={confirm.cancel}
    onConfirm={confirm.confirm}
  />

  {#if $toastStore}
    <div class={`toast ${$toastStore.type}`}>{$toastStore.message}</div>
  {/if}
</main>

<style>
  main {
    height: 100vh;
    height: 100dvh;
    width: 100vw;
    padding: 0.75rem;
    max-width: none;
    margin: 0;
    color: var(--foreground);
    display: flex;
    flex-direction: column;
    gap: 0.6rem;
    overflow: hidden;
  }

  .toolbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.5rem;
    border: 1px solid var(--border);
    padding: 0.5rem;
    background: var(--card);
  }

  h1 {
    margin: 0;
    font-size: 1rem;
    line-height: 1;
  }

  .toolbar-title {
    display: flex;
    align-items: center;
    gap: 0.45rem;
    min-width: max-content;
  }

  .version-chip {
    display: inline-flex;
    align-items: center;
    padding: 0.13rem 0.42rem;
    border: 1px solid var(--border);
    background: var(--muted);
    color: var(--muted-foreground);
    font-size: 0.68rem;
    font-family: monospace;
    letter-spacing: 0.01em;
  }

  .backend-chip {
    display: inline-flex;
    align-items: center;
    padding: 0.13rem 0.42rem;
    border: 1px solid var(--border);
    background: var(--secondary);
    color: var(--secondary-foreground);
    font-size: 0.7rem;
    letter-spacing: 0.01em;
    text-transform: lowercase;
  }

  .user-chip {
    display: inline-flex;
    align-items: center;
    padding: 0.13rem 0.55rem;
    border: 1px solid var(--border);
    background: var(--secondary);
    color: var(--secondary-foreground);
    font-size: 0.75rem;
    max-width: 180px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .toolbar-actions {
    display: flex;
    gap: 0.45rem;
    flex-wrap: wrap;
    justify-content: flex-end;
  }

  .content-region {
    flex: 1;
    min-height: 0;
    overflow: hidden;
    display: flex;
  }

  .content-region > :global(*) {
    min-width: 0;
    min-height: 0;
    width: 100%;
  }

  .status {
    width: 100%;
    align-self: flex-start;
    padding: 1rem;
    border: 1px solid var(--border);
    background: var(--card);
  }

  .status.error {
    border-color: var(--destructive);
    color: var(--destructive);
    background: hsl(0 100% 98%);
  }

  .form {
    display: grid;
    gap: 0.8rem;
  }

  label {
    display: grid;
    gap: 0.35rem;
    font-weight: 500;
    color: var(--muted-foreground);
  }

  .grid-2 {
    display: grid;
    gap: 0.8rem;
    grid-template-columns: 1fr;
  }

  .form-actions {
    display: flex;
    justify-content: flex-end;
    gap: 0.5rem;
    margin-top: 0.2rem;
  }

  .danger-zone {
    margin-top: 1.2rem;
    padding-top: 0.9rem;
    border-top: 1px solid var(--destructive);
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
  }

  .danger-zone-label {
    margin: 0;
    font-size: 0.78rem;
    font-weight: 600;
    color: var(--destructive);
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .toast {
    position: fixed;
    right: 1rem;
    bottom: 1rem;
    z-index: 1200;
    padding: 0.65rem 0.85rem;
    color: var(--primary-foreground);
    border: 1px solid var(--border);
    box-shadow: 0 12px 26px hsl(222 40% 8% / 0.16);
  }

  .toast.success {
    background: hsl(142 71% 45%);
  }

  .toast.error {
    background: var(--destructive);
  }

  @media (max-width: 1120px) {
    .toolbar {
      flex-direction: column;
      align-items: stretch;
    }

    .toolbar-actions {
      justify-content: flex-start;
    }
  }

  @media (min-width: 900px) {
    .grid-2 {
      grid-template-columns: 1fr 1fr;
    }
  }
</style>
